// Guides: plain data so the build-time prerenderer can use it. `tools` link to tool ids.
export const GUIDES = [
  {
    slug: 'dead-pixel-test-guide',
    title: 'How to Test for Dead and Stuck Pixels',
    description: 'Learn the difference between dead, stuck and hot pixels, how to test a screen properly in five minutes, and what to do if you find one.',
    tools: ['dead-pixel', 'red-screen', 'black-screen', 'white-screen'],
    intro: 'A few pixels that look wrong are common on new screens, and easy to miss until you stare at a plain color. A quick test with solid colors will find them.',
    sections: [
      { h: 'Dead, stuck and hot pixels', p: ['A dead pixel stays black on every color because it receives no light. A stuck pixel stays on one color, for example always red or green, while its neighbors change. A hot pixel stays white. Usually they are single tiny dots.', 'On OLED screens each pixel makes its own light, so a dead pixel shows as a tiny black dot on any bright color. On LCD screens a stuck pixel is the common fault.'] },
      { h: 'How to run the test', list: ['Clean the screen first, so dust or a fingerprint is not mistaken for a pixel.', 'Go to a dim room and set the screen to its normal brightness.', 'Open the Dead Pixel Test and press F for fullscreen.', 'Step through black, white, red, green and blue. Look at the whole screen at each step, then move closer and scan again.', 'Also try the cyan, magenta and yellow screens, which mix two subpixels and show partial faults.'] },
      { h: 'What the colors show', p: ['A black dot on white or any bright color is a dead pixel. A bright dot on black is a stuck or hot pixel. A dot that appears only on one color points to one faulty subpixel (the red, green or blue part of a pixel).'] },
      { h: 'What to do if you find one', p: ['Check how many there are and where. Most makers set a limit before they will replace a screen, and the rules differ by brand and by product, so read your warranty or return policy.', 'Stuck pixels sometimes recover on their own or after the screen has been on for a while. Dead pixels usually do not. Do not press hard on the glass, because that can damage the display.'] },
      { h: 'When to test', p: ['Test as soon as you unbox a monitor, phone or laptop, while returns are still easy. Test a used screen before you pay for it, and again after any repair.'] },
    ],
  },
  {
    slug: 'oled-burn-in-prevention',
    title: 'OLED Burn-In: What It Is and How to Prevent It',
    description: 'Understand OLED burn-in and image retention, what causes them, and simple habits that reduce the risk on phones, TVs and monitors.',
    tools: ['black-screen', 'gray-screen', 'white-screen'],
    intro: 'OLED screens give deep blacks and strong colors, but pixels that show the same bright image for a very long time can wear unevenly. Good habits keep the risk low.',
    sections: [
      { h: 'Burn-in and image retention', p: ['Image retention is a faint ghost that fades after a short time. Burn-in is permanent: the pixels that showed a static image, like a menu bar or channel logo, have aged faster than the rest.', 'Most people never see burn-in in normal use, but it is more likely with very bright, static content shown for many hours every day.'] },
      { h: 'Habits that help', list: ['Lower brightness when you do not need it high.', 'Use dark mode and auto-hide taskbars or menus where you can.', 'Turn the screen off, or let it sleep, instead of leaving a static page on.', 'Use a moving screensaver on a spare display rather than a still image.', 'Avoid leaving bright test screens, such as a pure white page, running for hours.'] },
      { h: 'Using test screens safely', p: ['Solid-color tests are fine for a few minutes. The OLED protection button on the screen pages shifts brightness slightly every 30 seconds, which varies pixel use while a screen is on for a long time.', 'To check for uneven wear, open the Gray Screen in a dim room and look for patches that are brighter or darker than the rest. Compare against other solid colors.'] },
      { h: 'What the maker offers', p: ['Many OLED phones, TVs and monitors have built-in pixel refresh or pixel shift features. Look in your device settings. Do not run a refresh routine more often than the manual suggests.'] },
    ],
  },
  {
    slug: 'how-to-clean-a-screen',
    title: 'How to Clean a Screen Safely',
    description: 'A simple, safe way to clean phone, laptop and monitor screens without damaging coatings, and how a white screen helps you spot every smudge.',
    tools: ['clean-screen', 'white-screen', 'black-screen'],
    intro: 'Most screen damage during cleaning comes from the wrong cleaner or too much pressure. A dry microfiber cloth does most of the work.',
    sections: [
      { h: 'What you need', list: ['A clean, dry microfiber cloth.', 'Optional: distilled water, to slightly dampen a second cloth.', 'Your device manual, in case your maker gives specific advice.'] },
      { h: 'Step by step', list: ['Turn the device off and unplug it if you can. A dark screen shows dust, a bright one shows smudges, so use both.', 'Open Screen Cleaning Mode to light the screen with plain white and see fingerprints clearly.', 'Wipe gently in one direction with the dry cloth.', 'If marks remain, slightly dampen a cloth with distilled water, wring it out, and wipe again.', 'Dry the screen with the other cloth. Switch back to a black screen to check for streaks and dust.'] },
      { h: 'What to avoid', list: ['Do not spray any liquid directly on the screen.', 'Avoid household cleaners, alcohol and ammonia unless your device maker says they are safe. They can damage coatings.', 'Do not use paper towels or rough cloths. They can scratch.', 'Do not press hard on the glass.'] },
      { h: 'Keeping it clean', p: ['Clean your hands before using touch screens, and keep a cloth where you use the device. A quick wipe each week prevents build-up.'] },
    ],
  },
  {
    slug: 'video-call-lighting-with-your-screen',
    title: 'How to Light Yourself for Video Calls Using Your Screen',
    description: 'Practical tips for looking good on camera in a dim room using a second screen as a soft light, including brightness, color temperature and placement.',
    tools: ['zoom-lighting', 'selfie-light', 'white-screen', 'ring-light'],
    intro: 'Good light matters more than a good camera. In a dim room, a bright screen near your camera is a free way to even out your face.',
    sections: [
      { h: 'Face the light', p: ['The most important rule is to put the light in front of you. A bright window or lamp behind you makes your face dark, because the camera adjusts for the brightest part of the picture.'] },
      { h: 'Use a second screen', p: ['If you light yourself with the same screen that shows the call, your call window disappears in fullscreen. A phone, tablet or second monitor works better. Open Zoom Lighting, press F, and place it just beside or behind your camera.'] },
      { h: 'Brightness and color', list: ['Start around 5000K and 90% brightness for a neutral look.', 'If your skin looks too pale, lower the warmth slider for a warmer light.', 'If it looks orange, raise the warmth for a cooler, whiter light.', 'Keep your own screen brightness high. A bigger screen gives softer light.'] },
      { h: 'Placement', list: ['Put the light slightly above eye level, near the camera.', 'Avoid hard side shadows by keeping the light close to straight ahead.', 'If you wear glasses and see a reflection, move the light slightly to the side.'] },
      { h: 'Quick checks', p: ['Look at your own video before the call. Your face should be brighter than the background, with no strong shadows. If the light is too harsh, lower brightness or move the screen back.'] },
    ],
  },
  {
    slug: 'ring-light-vs-screen-light',
    title: 'Ring Light vs Screen Light: Which Should You Use?',
    description: 'Compare a real ring light with a screen used as a light: brightness, quality, cost, portability and when each one makes sense.',
    tools: ['ring-light', 'zoom-lighting', 'selfie-light', 'makeup-mirror'],
    intro: 'A real ring light is brighter and more even. A screen is already in your hands and costs nothing. Here is how to choose.',
    sections: [
      { h: 'Brightness', p: ['A real ring light usually gives much more light than a phone or laptop screen. A screen is a good fill light in a dim room, but it will not overpower daylight or a bright room.'] },
      { h: 'Quality of light', p: ['A ring light surrounds the camera and gives even light with a circular catchlight in the eyes. A screen is a flat panel, so the light is softer and more spread out, which many people like for calls.'] },
      { h: 'Cost and convenience', list: ['Screen: free, always with you, and you can change color and warmth instantly.', 'Ring light: needs buying, space and a power source, but works with any device and stays on while you use your screen for other things.'] },
      { h: 'When a screen is enough', list: ['Video calls in a dim room.', 'Occasional selfies and quick photos.', 'Travel, when you do not want extra equipment.'] },
      { h: 'When to buy a real light', list: ['Regular streaming, content creation or product photography.', 'Rooms with a lot of competing light.', 'Long sessions where you need your whole screen for work.'] },
      { h: 'A good middle step', p: ['Try the Ring Light and Zoom Lighting pages first. If you find yourself using them every day, a real light is a sensible upgrade.'] },
    ],
  },
  {
    slug: 'check-monitor-brightness-and-uniformity',
    title: 'How to Check Your Monitor\'s Brightness, Contrast and Uniformity',
    description: 'A simple home routine to check brightness, black level, backlight bleed and uniformity with solid-color screens, no special equipment needed.',
    tools: ['brightness', 'gray-balance', 'gray-screen', 'black-screen', 'white-screen'],
    intro: 'You do not need a calibrator to spot the big problems. A few solid screens in a dim room tell you a lot about your display.',
    sections: [
      { h: 'Set up', list: ['Let the monitor warm up for about 20 minutes.', 'Dim the room lights and avoid reflections on the screen.', 'Reset your monitor to its default picture mode before testing.'] },
      { h: 'Brightness and contrast', p: ['Open Brightness Calibration. Adjust brightness until the darkest steps are just visible, and contrast until the brightest steps are still distinct. If they all merge, you are clipping detail.'] },
      { h: 'Black level and backlight bleed', p: ['Open the Black Screen in a dim room. On LCD screens you may see light glowing at the edges or corners. A small amount is normal. On OLED screens black should look completely dark.'] },
      { h: 'Uniformity and tint', p: ['Open the Gray Screen and then the White Screen. Look for darker or brighter patches and for any area with a color tint. Slight variation is common, but large or distracting patches are worth reporting if the screen is new.'] },
      { h: 'Limits of this test', p: ['This is a visual check. It cannot measure color accuracy. For accurate colors in photo or video work, use a hardware calibrator.'] },
    ],
  },
  {
    slug: 'white-noise-brown-noise-pink-noise',
    title: 'White, Pink and Brown Noise: What\'s the Difference?',
    description: 'A plain-language guide to white, pink and brown noise, how each sounds, and which to try for focus, relaxing or masking background sound.',
    tools: ['white-noise', 'pink-noise', 'brown-noise', 'sound-mixer'],
    intro: 'All three are steady background sounds. They differ in how much low and high pitch they contain, which changes how they feel.',
    sections: [
      { h: 'White noise', p: ['White noise has equal energy at every frequency, so it sounds bright, like a hiss or static. It is good at covering sudden sounds such as voices and traffic.'] },
      { h: 'Pink noise', p: ['Pink noise has less high-pitched energy than white noise, so it sounds softer and more balanced. Many people compare it to steady rainfall or wind.'] },
      { h: 'Brown noise', p: ['Brown noise is deeper still, with strong low frequencies. It sounds like a low rumble or a distant waterfall.'] },
      { h: 'Which to try', list: ['Masking voices and sudden sounds: white noise.', 'A softer everyday background: pink noise.', 'Deep, calm background for focus or relaxing: brown noise.'] },
      { h: 'Tips', list: ['Keep the volume low enough that you could still hold a conversation over it.', 'Use headphones or speakers that can play low sounds for brown noise.', 'Use the sleep timer if you play it at night.', 'Everyone is different. Try each for a few days.'] },
      { h: 'A note on claims', p: ['Many people find steady noise helps them focus or relax. Research on sleep and focus is mixed, and noise is not a medical treatment. If you have trouble sleeping often, speak with a health professional.'] },
    ],
  },
  {
    slug: 'pomodoro-technique-guide',
    title: 'The Pomodoro Technique: A Simple Guide',
    description: 'How the Pomodoro technique works, how to set your work and break lengths, and tips for staying focused with a timer.',
    tools: ['pomodoro', 'countdown-timer', 'focus-mode', 'brown-noise'],
    intro: 'The Pomodoro technique breaks work into short timed sessions with breaks in between. It is simple, free and easy to adjust.',
    sections: [
      { h: 'The basic method', list: ['Choose one task.', 'Work for 25 minutes with no interruptions.', 'Take a 5-minute break.', 'After four sessions, take a longer break of 15 to 30 minutes.'] },
      { h: 'Why it works for many people', p: ['A short, clear deadline makes it easier to start. Regular breaks help you rest before you get tired. Seeing finished sessions gives a sense of progress.'] },
      { h: 'Adjust it to you', list: ['If 25 minutes feels too short for deep work, try 40 or 50 with a longer break.', 'If you struggle to start, try 10-minute sessions.', 'Use the break to stand up, drink water and look away from the screen.'] },
      { h: 'Tips for staying on track', list: ['Write down distractions and handle them after the session.', 'Silence notifications while the timer runs.', 'Try quiet background sound, such as brown noise.', 'Do not skip breaks. They are part of the method.'] },
      { h: 'Using the tools', p: ['The Pomodoro Timer remembers your work and break lengths, keeps the time in the tab title and beeps at the end of each session. The Countdown Timer is useful for one-off tasks.'] },
    ],
  },
]

export const getGuide = (slug) => GUIDES.find((g) => g.slug === slug)
